<a href="https://colab.research.google.com/github/rudrabhaskar424-design/python/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Gello world", 45)

Gello world 45


In [ ]:
print(29*66)

1914


In [ ]:
nzme = "rudra"
age=33
print(type(nzme))
print(type(age))

<class 'str'>
<class 'int'>


In [ ]:
a,c = 1,2.0
sum=a+c
sum

3.0

In [ ]:
str = "Rudra askar"
r = len(str)
r

11

In [ ]:
str = "rudra sapat"
print(str[:6])
print(str[3])
print(str[:])

rudra 
r
rudra sapat


In [ ]:
str = "i am a leader"
print(str.endswith("er"))
print(str.capitalize())
print(str.find("l"))
print(str.replace("a","an"))
print(str.upper())
print(str.lower())
print(str.isalpha())

True
I am a leader
7
i anm an leander
I AM A LEADER
i am a leader
False


In [ ]:

marks= int(input("enter marks:- "))
if (marks>=90):
  print("grade A")
elif(marks>=80 and marks<90):
    print("grade 2")
elif(marks>=70 and marks<80):
    print("grade c")
else:
    print("grade d")



enter marks:- 67
grade d


In [ ]:
marks=[56,43,98,65,98]
print(marks[4])
marks[1]="Arjun"
print(marks)


98
[56, 'Arjun', 98, 65, 98]


In [ ]:
list=[4,6,3,0,8]
list.pop(1)

type(list)
list.reverse()
print(list)



[8, 0, 3, 4]


In [ ]:
tup = []
tup.append(input("enter the movie:- "))
tup.append(input("enter the movie:- "))
tup.append(input("enter the movie:- "))
tup

enter the movie:- De dana dan
enter the movie:- Kris
enter the movie:- Koi mil Gaya


['De dana dan', 'Kris', 'Koi mil Gaya']

In [ ]:
my_dict = {"name":"Rudra",
        "sub":{"phy":34,
               "chem":67,
               "math":89},
        "marks":[32,33,43,43,4]}

my_dict.keys()


dict_keys(['name', 'sub', 'marks'])

In [ ]:
my_dict.values()

dict_values(['Rudra', {'phy': 34, 'chem': 67, 'math': 89}, [32, 33, 43, 43, 4]])

In [ ]:
my_dict.items()

dict_items([('name', 'Rudra'), ('sub', {'phy': 34, 'chem': 67, 'math': 89}), ('marks', [32, 33, 43, 43, 4])])

In [ ]:
print(my_dict.get("sub"))

{'phy': 34, 'chem': 67, 'math': 89}


In [ ]:
my_dict = {"name":"Rudra",
        "sub":{"phy":34,
               "chem":67,
               "math":89},
        "marks":[32,33,43,43,4]}

my_dict["name"] = "Rudra_Bhaskar"
my_dict.keys()



dict_keys(['name', 'sub', 'marks'])

In [ ]:
my_dict.update({"Roll No": [23,43,45,65,76]})
my_dict

{'name': 'Rudra_Bhaskar',
 'sub': {'phy': 34, 'chem': 67, 'math': 89},
 'marks': [32, 33, 43, 43, 4],
 'Roll No': [23, 43, 45, 65, 76]}

In [ ]:
set = {13,6,8,9}
set2 = {1,2,2,3,5,5,8,8}
set.union(set2)


{1, 2, 3, 5, 6, 8, 9, 13}

In [ ]:
set.intersection(set2)

{8}

In [ ]:
set.add(44)
set

{6, 8, 9, 13, 44}

In [ ]:
set.remove(6)
set

{8, 9, 13, 44}

In [ ]:
set2.pop()
set2


{3, 5, 8}

In [ ]:
str = "rudra bhaskar"
for var in str:
  print(var)
else:
    print("End")

r
u
d
r
a
 
b
h
a
s
k
a
r
End


In [ ]:
for var in range(10):
     pass
     if(var>5):
       pass
print("djfnjfjfjf")

djfnjfjfjf


In [ ]:
def sum(a,b):
  s = a + b
  return s

print(sum(2,3))

5


In [ ]:
i=0
while(i<=6):
  if(i==3):
    i+=1
    continue
  print(i)
  i+=1

0
1
2
4
5
6


In [ ]:
i=0
while(i<=8):
  print(i)
  if(i==6):
     break
  i+=1

0
1
2
3
4
5
6


In [ ]:
var=[3,4,3,43,5,54,5,55,45,87]
def lengh(list):
  print(range(2,5))

lengh(var)


range(2, 5)


In [ ]:
def show(n):
  if(n==0):
    return
  print(n)
  show(n-1)

show(5)

5
4
3
2
1


In [ ]:
def fact(n):
  if(n==0 or n==1):
    return 1
  else:
    return n * fact(n-1)
print(fact(5))

120


In [ ]:

f=open("//content//sample3.txt","r")
content = f.read()
print(content)
f.close()

Quod equidem non reprehendo;
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Quae enim adhuc protulisti, popularia sunt, ego autem a te elegantiora desidero. Duo Reges: constructio interrete. Tum Lucius: Mihi vero ista valde probata sunt, quod item fratri puto. Bestiarum vero nullum iudicium puto. Nihil enim iam habes, quod ad corpus referas; Deinde prima illa, quae in congressu solemus: Quid tu, inquit, huc? Et homini, qui ceteris animantibus plurimum praestat, praecipue a natura nihil datum esse dicemus?

Iam id ipsum absurdum, maximum malum neglegi. Quod ea non occurrentia fingunt, vincunt Aristonem; Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Fieri, inquam, Triari, nullo pacto potest, ut non dicas, quid non probes eius, a quo dissentias. Equidem e Cn. An dubium est, quin virtus ita maximam partem optinea

In [ ]:
f=open("//content//sample3.txt","w")
cop=f.write("i am Rudra Bhaskar")
print(cop)
f.close()
print(f)

18
<_io.TextIOWrapper name='//content//sample3.txt' mode='w' encoding='utf-8'>


In [ ]:
f=open("//content//sample3.txt","r")
content = f.read()
print(content)
f.close()

i am Rudra Bhaskar


In [ ]:
f=open("//content//sample3.txt","a")
cop=f.write("i am Rudra Bhaskar")
print(cop)
f.close()

18


In [ ]:
with open("//content//sample3.txt","r") as f:
  data = f.read()
  print(data)

i am Rudra Bhaskari am Rudra Bhaskari am Rudra Bhaskar


In [ ]:
import os
os.remove("//content//sample3.txt")


In [ ]:
with open("practice.txt","w") as f:
  f.write(" Hi everyone\n We are learning file i/o \n")
  f.write(" using Java.\n I am learning programming in Java.")



In [ ]:
with open("practice.txt","r") as f:
   data = f.read()
   new_data = data.replace("Java","Python")
   print(new_data)



 Hi everyone
 We are learning file i/o 
 using Python.
 I am learning programming in Python.


In [ ]:
word = "learn"
with open("practice.txt","r") as f:
  data = f.read()
  if(data.find(word)!= -1):
    print("found")
  else:
     print("not found")

found


In [ ]:
from re import S
class Student:
  name ="Karan kumar"
s1 = Student()
print(s1.name)


Karan kumar


In [ ]:
class student:
  def __init__(self,fullname):
    self.name = fullname
    print("adding new student in dataase..")
s1 = student("Rudra Bhaskar")
print(s1.name)

adding new student in dataase..
Rudra Bhaskar


In [ ]:
class student:
  college_name = "ABC college"
  def __init__(self,name,marks):
    self.name = name
    self.marks = marks
    print("adding new student in database..")
s1 = student("Rudra Bhaskar", 98)
del s1.name
del s1
print(s1.marks)
print(s1.college_name)

adding new student in database..


NameError: name 's1' is not defined

In [ ]:
class student:
      def __init__ (self, fullname):
       self.name = fullname
      def hello(self):
       print("hello",self.name)
s1 = student("Rudra Bhaskar")
s1.hello()

hello Rudra Bhaskar


In [ ]:
class student:
  def __init__ (self,name,marks):
    self.name = name
    self.marks = marks
  def get_avg(self):
    sum = 0
    for val in self.marks:
     sum += val
    print("your avg score is :",sum/3)
s1 = student("Rudra Bhaskar", [23,45,87])
s1.get_avg()

your avg score is : 51.666666666666664


In [ ]:
class student:
  @staticmethod
  def college():
    print("ABC college")
s1 = student()
s1.college()


ABC college


In [ ]:
class car:
  def __init__(self):
     self.acc = False
     self.brk = False
     self.clutch = False
  def start(self):
      self.clutch = True
      self.acc = True
      print("car started..")
car1 = car()
car1.start()

car started..


In [ ]:
class Account:
  def __init__ (self,acc_no,acc_pass):
     self.acc_no = acc_no
     self.__acc_pass = acc_pass
acc1 = Account("12345","abcde")
print("Account Number:-",acc1.acc_no)



Account Number:- 12345


In [ ]:
class car:
  @staticmethod
  def start():
    print("Car Started")
  @staticmethod
  def stop():
    print("car stopped")
class Toyatacar(car):
  def __init__ (self,name):
    self.name = name
car1 = Toyatacar("Fortuner")
car2 = Toyatacar("prius")
print(car1.start())
print(car2.name)
car2.stop()

Car Started
None
prius
car stopped


In [ ]:
class car:
  @staticmethod
  def start():
    print("car started")
  @staticmethod
  def stop():
    print("car stopped")
class Toyotacar(car):
  def __init__(self,brand):
    self.brand = brand
class Fortuner(Toyotacar):
  def __init__ (self,type,brand):
   super().__init__(brand)
   self.type = type
car1 = Fortuner("diesel","oyata")
car1.start()
car1.brand


car started


'oyata'

In [ ]:
class Person:
  name= "anonmous"
  @classmethod
  def change_Name(cls,name):
    cls.name = name
p1 = Person()
p1.change_Name("Rudra Bhaskar")
print(p1.name)


Rudra Bhaskar


In [ ]:
class student:
  def __init__(self,phy,chem,math):
    self.phy = phy
    self.chem = chem
    self.math = math
  @property
  def percentage(self):
    return str((self.phy+self.chem+self.math)/3)+" %"
stu1 = student(87,54,89)
print(stu1.percentage)
stu1.phy = 99
print(stu1.percentage)

76.66666666666667 %
80.66666666666667 %


In [ ]:
class complex:
  def __init__ (self,real,img):
    self.real = real
    self.img = img
  def showNumber(self):
    print(self.real,"i+", self.img,"j")
  def __add__ (self,num2):
    newReal = self.real + num2.real
    newImg = self.img + num2.img
    return complex(newReal,newImg)
num1 = complex(1,3)
num1.showNumber()
num2 = complex(4,6)
num2.showNumber()
num3 = num1 + num2
num3.showNumber()


1 i+ 3 j
4 i+ 6 j
5 i+ 9 j


In [ ]:
import numpy as np
x = np.array([1,3,6,9])
print(x)
print(type(x))



[1 3 6 9]
<class 'numpy.ndarray'>


In [ ]:
l = []
for i in range(1,5):
  var = int(input("enter the value"))
  l.append(var)
print(l)


enter the value45
enter the value56
enter the value78
enter the value98
[45, 56, 78, 98]


In [ ]:
y = np.array([1,2,3,4,5])
print(y)
print(y.ndim)

[1 2 3 4 5]
1


In [ ]:
ar2 = np.array([[1,2,3,44,5],[6,7,8,9,0,]])
print(ar2)


[[ 1  2  3 44  5]
 [ 6  7  8  9  0]]


In [ ]:
ar2 = np.array([[[1,2,3,44,5],[6,7,8,9,0,],[3,4,5,6,7]]])
print(ar2)

[[[ 1  2  3 44  5]
  [ 6  7  8  9  0]
  [ 3  4  5  6  7]]]


In [ ]:
import numpy as np
arn = np.array([1,2,3,4,5], ndmin = 10)
print(arn)
print(arn.ndim)


[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [ ]:
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)
print (type(ar_zero))


[0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
ar = np.ones(4)
print(ar)

[1. 1. 1. 1.]


In [ ]:
are = np.empty(4)
print(are)

[1. 1. 1. 1.]


In [ ]:
var = np.eye(7)
print(var)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
var = np.arange(5)
print(var)

[0 1 2 3 4]


In [ ]:
var = np.linspace(1,36, 6)
print(var)

[ 1.  8. 15. 22. 29. 36.]


In [ ]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.05523458 0.95177252 0.39561965 0.8507826 ]


In [ ]:
var = np.random.randn(7)
print(var)

[ 0.64071438 -1.20761276  1.37033347  2.60237353  0.24531926  0.51350271
 -2.23536301]


In [ ]:
var3 = np.random.ranf(4)
print(var3)

[0.76723077 0.21387473 0.14263112 0.69852055]


In [ ]:
var4 = np.random.randint(2,90,18)
print(var4)

[58 64 17 73 37 20 67 12  8 41 17 43 64 40 53 70 76 41]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5], dtype = np.int8)
print("Data Type: ", var.dtype)


Data Type:  int8


In [ ]:
x2 = np.array([1,2,3,4,5])
new = np.float32(x2)
print("Data type:-", x2.dtype)
print("Data Type", new.dtype)
print(x2)
print(new)

Data type:- int64
Data Type float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
varadd = np.add(var,3)
print(varadd)

[4 5 6 7 8]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
var1 = np.array([1,2,3,4,5])
varadd = np.add(var,var1)
print(varadd)

[ 2  4  6  8 10]


In [ ]:
var = np.array([[1,2,3,4,5],[5,6,7,8,9]])
var1 = np.array([[9,8,7,6,5],[5,4,3,2,1]])
varadd = np.add(var,var1)
print(varadd)

[[10 10 10 10 10]
 [10 10 10 10 10]]


In [ ]:
var = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)





[1 0 0 0]


In [ ]:
import numpy as np
var = np.array([3,4,2,8,9,0,6,8])
print("min: ",np.min(var))

print("max", np.max(var))

min:  0
max 9


In [ ]:
import numpy as np
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1, axis= 1))


[1 5]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
print(np.sqrt(var))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
import numpy as np
var2 = np.array([1,2,3])
print(np.cumsum(var2))

[1 3 6]


In [ ]:
import numpy as np
var3 = np.array([[1,2],[3,4]])
print(var3)
print(var3.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
import numpy as np
var4 = np.array([1,2,3,4], ndmin = 4)
print(var4)
print(var4.ndim)
print(var4.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [ ]:
import numpy as np
var1 = np.array([1,2,3,4,5,6])
x = var1.reshape(3,2)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()
x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)
print(x1.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np
var1 = np.array([1,1,1])
print(var1.shape)
print(var1)
var2 = np.array([[1],[2],[3]])
print(var2)
print(var1 + var2)

(3,)
[1 1 1]
[[1]
 [2]
 [3]]
[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print(var[1])

2


In [ ]:
import numpy as np
var = np.array([[[9,8,7,6],[4,5,6,7],[3,4,5,6]],[[1,2,3,4],[5,6,7,8],[9,8,7,6]]])
print(var[0,0,2])
print(var[1,1,3])

7
8


In [ ]:
import numpy as np
var =np.array([1,2,3,4,5,6,7,8,9,10])
print(var)
print("2 to 10", var[1:])

[ 1  2  3  4  5  6  7  8  9 10]
2 to 10 [ 2  3  4  5  6  7  8  9 10]


In [ ]:
var[1::2]

array([ 2,  4,  6,  8, 10])

In [ ]:
var1 =np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(var1)
print(var1[1,1:])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 8  9 10 11 12]


In [ ]:
import numpy as np
var = np.array([9,8,7,6,5,4,3,2,1])
print(var)
for i in var:
    print(i)


[9 8 7 6 5 4 3 2 1]
9
8
7
6
5
4
3
2
1


In [ ]:
var1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(var1)
for j in var1:
  print(j)
  for l in j:
      print(l)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5]
1
2
3
4
5
[6 7 8 9 0]
6
7
8
9
0


In [ ]:
var3 = np.array([[[9,8,7,6,5],[5,4,3,2,1],[1,2,3,4,5]]])
print(var3)
for k in var3:
  for j in k:
    for h in j:
      print(h)

[[[9 8 7 6 5]
  [5 4 3 2 1]
  [1 2 3 4 5]]]
9
8
7
6
5
5
4
3
2
1
1
2
3
4
5


In [ ]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
for i in np.nditer(var3):
  print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
9
8
7
6
1
2
3
4


In [ ]:
var4 = np.array([[[9,8,7],[1,2,3]]])
for i,d in np.ndenumerate(var3):
  print(i,d)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [ ]:
import numpy as np
var = np.array([1,2,3,4])
co = var.copy()
print("var", var)
print("copyy",co)
print(type(co))


var [1 2 3 4]
copyy [1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
vi = co.view()
print("view", vi)


view [1 2 3 4]


In [ ]:
var = np.array([1,2,3,4,5])
var[1] = 40
co = var.copy()

print("var: ",var)
print("copy: ",co)

var:  [ 1 40  3  4  5]
copy:  [ 1 40  3  4  5]


In [ ]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 5 6 7 8]


In [ ]:
var = np.array([[1,2],[3,4]])
var1 = np.array([[9,8],[6,7]])
ar = np.concatenate((var,var1), axis = 1)
ar1 = np.concatenate((var,var1), axis = 0)
print(var)
print(var1)
print(ar)
print(ar1)

[[1 2]
 [3 4]]
[[9 8]
 [6 7]]
[[1 2 9 8]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [9 8]
 [6 7]]


In [ ]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([9,8,7,6])
ar = np.hstack((var1,var2)) #row
ar2 = np.vstack((var1,var2)) #column
ar2 = np.dstack((var1,var2)) #height
print(ar)
print(ar1)
print(ar2)

[1 2 3 4 9 8 7 6]
[[1 2]
 [3 4]
 [9 8]
 [6 7]]
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5])
print(var)
ar = np.array_split(var,6)
print(ar)
print(ar[0])
print(ar[1])

[1 2 3 4 5]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([], dtype=int64)]
[1]
[2]


In [ ]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
ar = np.array_split(var1,3)
ar1 = np.array_split(var1,2,axis = 1)
print(ar)
print(ar1)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])
x = np.where(var == 2)
print(x)
x1 = np.where(var%2 == 0)
print(x1)

(array([1]),)
(array([1, 3, 5]),)


In [ ]:
import numpy as np
var1 = np.array([1,2,3,4,5,6,5,8])
x1 = np.searchsorted(var1,5)
print(x1)

4


In [ ]:
var2 =np.array([4,2,5,7,5])
print(np.sort(var2))


[2 4 5 5 7]


In [ ]:
var2 = np.array([[4,2,3],[6,9,5],[5,0,1]])
print(np.sort(var2))


[[2 3 4]
 [5 6 9]
 [0 1 5]]


In [ ]:
var3 = np.array(["a","s","t","y"])
f = [True,False,False,True]
new_a = var3[f]
print(new_a)

['a' 'y']


In [ ]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(var)
print(var)

[4 5 6 1 7 8 2 3]


In [ ]:
import numpy as nl
var1 = np.array([1,2,3,4,5,6,7,6,3,1,3])
x = np.unique(var1)
print(x)
x1 = np.unique(var1,return_index = True, return_counts = True)
print(x1)

[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 4, 5, 6]), array([2, 1, 3, 1, 1, 2, 1]))


In [ ]:
import numpy as np
var2 = np.array([1,2,3,4,5,6,7,8,9,0])
y = np.resize(var2,(2,2,2))
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
var2 = np.array([[1,22,3],[4,5,6]])
y = var2.flatten()
print(y)
print("flatten :-", var2.flatten(order = "f"))
print("ravel:-", np.ravel(var2))

[ 1 22  3  4  5  6]
flatten :- [ 1  4 22  5  3  6]
ravel:- [ 1 22  3  4  5  6]


In [ ]:
import numpy as np
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,2,40)
v1 = np.insert(var,(2,4),40)
print(v)
print(v1)
print(np.append(var,98))

[1 2 3 4]
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]
[ 1  2  3  4 98]


In [ ]:
var1 = np.array([[1,2,3],[4,5,6]])
print(np.insert(var1,2,4,axis = 0))
print(np.insert(var1,2,[22,23],axis=1))
print(np.insert(var1,2,[22,23,24],axis=0))
print(np.append(var1,[[45,34,78]],axis=0))

[[1 2 3]
 [4 5 6]
 [4 4 4]]
[[ 1  2 22  3]
 [ 4  5 23  6]]
[[ 1  2  3]
 [ 4  5  6]
 [22 23 24]]
[[ 1  2  3]
 [ 4  5  6]
 [45 34 78]]


In [ ]:
import numpy as np
var1 = np.array([1,2,3,4,5,6])
print(var1)
d = np.delete(var1,2)
print(d)

[1 2 3 4 5 6]
[1 2 4 5 6]


In [ ]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var))



[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [ ]:
var = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[3,4],[6,7]])
print(var * var2)
print(var.dot(var2))

[[15 18]
 [33 40]]
[[15 18]
 [33 40]]


In [ ]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
#print(np.transpose(var))
print(var.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print(np.linalg.inv(var3))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print(np.linalg.matrix_power(var4,2))
print(np.linalg.matrix_power(var4,0))
print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [ ]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print(np.linalg.det(var5))


[[1 2]
 [3 4]]
-2.0000000000000004
